HOST:
  DOMAIN: "localhost"
  PORT: 8000
  CONTEXT_TIMEOUT: 30
  SERVER_DEBUG: false #set to false in production
  SERVER_WRITE_TIMEOUT: 5
  SERVER_READ_TIMEOUT: 5
  SERVER_IDLE_TIMEOUT: 60 # seconds
  SERVER_REQUEST_TIMEOUT: 10
  SSL:
    SSL_ENABLE: false # SSL mode, by default false
    CERT_FILE: "" # Path SSL certificate file location, when SSL_ENABLE set to true. This must be required.
    KEY_FILE: "" # Path SSL key certificate file location, when SSL_ENABLE set to true. This must be required.
  CORS_CONFIG: # CORS Config
    WITH_CREDENTIALS: true
    ALLOW_ORIGINS: # This header defines a list of origins that may access the resource.
      - "*" # Wildcard its not specified, all domain origin will be passed

    ALLOW_HEADERS: # AllowHeaders determines the value of the Access-Control-Allow-Headers response header.
                     # This header is used in response to a preflight request to indicate which HTTP headers can be used when making the actual request.
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "X-Request-Id"
      - "Retry-After"
      - "X-RateLimit-Limit"
      - "X-RateLimit-Remaining"
      - "X-RateLimit-Reset"
      - "Accept-Language"
      - "Authorization"

    ALLOW_METHODS:
      - "GET"
      - "POST"
      - "DELETE"
      - "PUT"
      - "PATCH"
      - "OPTIONS"

# Database setup
POSTGRES:
  DATABASE_HOST: "localhost"
  DATABASE_PORT: 5432
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: ""
  DATABASE_NAME: ""
  DATABASE_SSL_MODE: "disable"
  DATABASE_TIMEZONE: "Asia/Jakarta"

# i18n language setup
I18N:
  BUNDLE_DIR: "./i18n"

# UI setup
UI:
  PUBLIC_URL: '/'
  API_URL: 'http://localhost:8000/'
  BASE_URL: ''
  API_BASE_URL: ''

# Sonyflake
SONYFLAKE:
  START_TIME_UNIX: 1700000000
  MACHINE_ID: 1