// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package codenomcmd

import (
	"context"
	"github.com/codenomdev/viona/internal/apps"
	"github.com/codenomdev/viona/internal/apps/routes"
	"github.com/codenomdev/viona/internal/modules/plugin"
	"github.com/codenomdev/viona/internal/modules/setting"
	"github.com/codenomdev/viona/internal/modules/setting/repository"
	"github.com/codenomdev/viona/internal/modules/setting/service"
	"github.com/codenomdev/viona/internal/modules/static"
	"github.com/codenomdev/viona/pkg/config"
	"github.com/codenomdev/viona/pkg/db/gorm"
	"github.com/codenomdev/viona/pkg/log"
)

// Injectors from wire.go:

func initApplication(ctx context.Context, cfg *config.Config, log2 log.Logger) (*apps.AppServer, func(), error) {
	db, cleanup, err := gorm.NewPgsqlDB(cfg, ctx)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepository(db)
	serviceService := service.NewService(db, repositoryRepository)
	handler := setting.NewHandler(serviceService)
	route := setting.NewRoute(handler)
	pluginHandler := plugin.NewHandler()
	pluginRoute := plugin.NewRoute(pluginHandler)
	registerApiRoutes := routes.NewApiRoutes(route, pluginRoute)
	staticHandler := static.NewStaticHandler()
	staticRoutes := static.NewStaticRoute(staticHandler)
	uiRoutes := routes.NewUIRoutes(staticRoutes)
	appServer := apps.NewApp(cfg, log2, registerApiRoutes, uiRoutes)
	return appServer, func() {
		cleanup()
	}, nil
}
