package routes

import (
	"io/fs"

	"github.com/codenomdev/viona/internal/modules/static"
	"github.com/codenomdev/viona/pkg/config"
	"github.com/codenomdev/viona/ui"
	"github.com/labstack/echo/v4"
)

type (
	UIRoutes struct {
		r *static.Routes
	}
)

func NewUIRoutes(
	r *static.Routes,
) *UIRoutes {
	return &UIRoutes{
		r: r,
	}
}

// Register a new static resource which generated by ui directory
func (a *UIRoutes) MapBaseStatic(e *echo.Echo, cfg *config.Config) {
	assets, err := fs.Sub(
		ui.Build,
		"build/static",
	)
	if err != nil {
		panic(err)
	}

	e.StaticFS(
		"/static",
		assets,
	)
	a.r.RegisterStatic(e)
}
